### ISSUE TITLE
Feature Request: Restore background image during Shutdown and when pressing CTRL+ALT+DEL

### ISSUE THREAD

**Issue by Skyyblaze** [xxxman360/LogonVistaOrb#4]
I know this might technically push the boundaries a bit for an application called LogonVistaOrb but I wanted to ask, would it be possible to restore the background image during pre-login tasks such as updating, shutdown and when pressing CTRL+ALT+DEL and calling the Task Manager menu.

Windows Vista and Windows 7 both had this functionality, Windows 10 replaced the background with any given Accent Color and Windows 11 made it black. Technically the function still exists in newer versions of Windows as when you shutdown or restart from the login screen the current lockscreen image will still be shown in the background. Here are two screenshots I took in a VM to illustrate what I mean.

Shutting down normally in Windows 10:

![grafik](https://github.com/user-attachments/assets/472b8104-f24b-432a-b195-538236c5e186)

Shutting down from the lock screen:

![grafik](https://github.com/user-attachments/assets/f006de59-ff82-4e18-b669-b337f270aa27)

So it feels when the shutdown process is started as the SYSTEM? user it's what causes the image to be shown. Could LogonVistaOrb perhaps tackle that? I feel it would make the experience feel complete.

**Comment by xxxman360** [comment]
I'm afraid that is pushing the limit of what LogonVistaOrb is designed for, especially since the process quits after logging in. Even if I were to modify the shutdown task (that initializes LogonVistaOrb for the next boot), I have no idea how I would be injecting an image into the background of LogonUI.

If you want better customization of your login screen, see [ConsoleLogonHook](https://github.com/wiktorwiktor12/ConsoleLogonHook). This neat software comes with a 1:1 recreation of the Windows 7 login screen (Which is identical to Vista's once you replace a few images), furthermore, you can replace the background with your own image using Resource Hacker if you'd like to have a custom login wallpaper.

**Comment by Skyyblaze** [comment]
That's what I figured but I thought asking might not hurt. I haven't heard of ConsoleLogonHook before but it seems quite interesting if a touch too invasive for me as it seems to outright replace Windows' login-screen which feels a little insecure.

**Comment by xxxman360** [comment]
Well, I use it everyday. Probably more secure than injecting data into the login screen. If you don't want to use it, that's fine. I just figured it would help.

**Comment by Skyyblaze** [comment]
Well I suppose it can't hurt to try it out at least haha. Thanks for the tip either way!
